In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.3'

In [3]:
data = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

In [4]:
data.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [5]:
len(data)

9704

In [6]:
data['fuel_type'].nunique()

2

In [7]:
data.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [8]:
data[data["origin"]=='Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [9]:
data['horsepower'].median()

np.float64(149.0)

In [10]:
most_freq = data['horsepower'].mode()[0]

In [11]:
data['horesepower'] = data['horsepower'].fillna(most_freq)

In [12]:
data['horsepower'].median()

np.float64(149.0)

In [13]:
first7 = data[data["origin"]=='Asia'][['vehicle_weight','model_year']].head(7)

In [14]:
first7

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [15]:
X= first7.to_numpy()

In [16]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [17]:
XTX = X.T @ X

In [18]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [19]:
XTX_inv = np.linalg.inv(XTX)

In [20]:
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [21]:
y = [1100,1300,800,900,1000,1100,1200]

In [22]:
y = np.array(y)

In [23]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [24]:
w = XTX_inv @ X.T @ y

In [26]:
print(w.sum())

0.5187709081074016
